Repository Solvro/web-topwr, pull requests merged in 2025-10, with the labels that each got.

#44 feat: create event calendar
  package-lock.json
  package.json
  src/app/calendar_events/create/page.tsx
  src/app/calendar_events/edit/[id]/page.tsx
  src/app/calendar_events/layout.tsx
  src/app/calendar_events/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/abstract/abstract-resource-list.tsx
  src/components/abstract/create-button.tsx
  src/components/abstract/edit-button.tsx
  src/components/abstract/resource-form/client.tsx
  src/components/abstract/resource-form/index.tsx
  src/components/calendar/all-events-modal.tsx
  src/components/calendar/day-button.tsx
  src/components/calendar/index.tsx
  src/components/delete-button-with-dialog.tsx
  src/components/inputs/date-time-picker.tsx
  src/components/ui/dialog.tsx
  src/config/calendar-events.tsx
  src/config/constants.ts
  src/config/enums.ts
  src/config/polish.ts
  src/config/resources.ts
  src/lib/helpers/calendar.ts
  src/middleware.ts
  src/schemas/resources.ts
  src/stores/calendar.ts
  src/tests/mocks/handlers.ts
  src/types/api.ts
  src/types/calendar.ts
  src/types/forms.ts
Labels: size/XXL

#25 feat: order widget
  package-lock.json
  package.json
  src/app/banners/page.tsx
  src/app/guide_articles/page.tsx
  src/app/student_organizations/page.tsx
  src/components/abstract/abstract-resource-layout.tsx
  src/components/abstract/abstract-resource-list.tsx
  src/components/abstract/resource-form/client.tsx
  src/components/abstract/resource-list/drag-handle.tsx
  src/components/abstract/resource-list/index.tsx
  src/components/abstract/resource-list/infinite-scroller.test.tsx
  src/components/abstract/resource-list/infinite-scroller.tsx
  src/components/abstract/resource-list/item.tsx
  src/components/abstract/resource-list/orderable-item-wrapper.test.tsx
  src/components/abstract/resource-list/orderable-item-wrapper.tsx
  src/components/abstract/resource-list/sort-filters.test.tsx
  src/components/abstract/resource-list/sort-filters.tsx
  src/components/pagination.tsx
  src/config/constants.ts
  src/config/enums.ts
  src/config/resources.ts
  src/lib/helpers/backend.ts
  src/lib/helpers/transformations.ts
  src/lib/helpers/typescript.ts
  src/schemas/forms.ts
  src/tests/mocks/functions.ts
  src/tests/setup.ts
  src/types/api.ts
  src/types/app.ts
Labels: size/XL

#75 refactor(layout): separate authenticated & non-authenticated paths
  src/app/(authenticated)/banners/create/banners-create-page.test.tsx
  src/app/(authenticated)/banners/create/page.tsx
  src/app/(authenticated)/banners/edit/[id]/banners-edit-page.test.tsx
  src/app/(authenticated)/banners/edit/[id]/page.tsx
  src/app/(authenticated)/banners/layout.tsx
  src/app/(authenticated)/banners/page.tsx
  src/app/(authenticated)/calendar_events/create/page.tsx
  src/app/(authenticated)/calendar_events/edit/[id]/page.tsx
  src/app/(authenticated)/calendar_events/layout.tsx
  src/app/(authenticated)/calendar_events/page.tsx
  src/app/(authenticated)/error/[code]/page.tsx
  src/app/(authenticated)/guide_articles/create/page.tsx
  src/app/(authenticated)/guide_articles/edit/[id]/page.tsx
  src/app/(authenticated)/guide_articles/layout.tsx
  src/app/(authenticated)/guide_articles/page.tsx
  src/app/(authenticated)/layout.tsx
  src/app/(authenticated)/page.tsx
  src/app/(authenticated)/student_organizations/create/page.tsx
  src/app/(authenticated)/student_organizations/edit/[id]/page.tsx
  src/app/(authenticated)/student_organizations/layout.tsx
  src/app/(authenticated)/student_organizations/page.tsx
  src/app/(unauthenticated)/layout.tsx
  src/app/(unauthenticated)/login/form.tsx
  src/app/(unauthenticated)/login/login-page.test.tsx
  src/app/(unauthenticated)/login/page.tsx
  src/app/layout.tsx
  src/components/content-wrapper.tsx
  src/components/logout-button.tsx
  src/components/navbar.tsx
Labels: enhancement, size/M

#82 feat(arl): add item id
  package-lock.json
  package.json
  src/app/(authenticated)/banners/create/banners-create-page.test.tsx
  src/app/(authenticated)/banners/edit/[id]/banners-edit-page.test.tsx
  src/components/abstract/resource-list/drag-handle.tsx
  src/components/abstract/resource-list/infinite-scroller.tsx
  src/components/abstract/resource-list/item.tsx
  src/components/delete-button-with-dialog.tsx
  src/components/ui/badge.tsx
  src/components/ui/button/variants.ts
  src/config/resources.ts
Labels: enhancement, size/M
